### ISSUE TITLE
xdeb ux

### ISSUE THREAD

**Issue by 2trvl** [toluschr/xdeb#21]
Why is it possible to create a package with conflicts like: everything is ok, but I will rewrite your bin / lib?

Perhaps aborting and --force option is more appropriate

Well, or why shouldn't the utility itself solve simple conflicts related to destdir
Like we have 1 distribution and we know exactly what will break the system

**Comment by toluschr** [comment]
> Why is it possible to create a package with conflicts like: everything is ok, but I will rewrite your bin / lib?

The system you use for conversion may not be the one you install it on. This is rather an issue with XBPS not checking for conflicts. I was told that this would be fixed in the future when asking on the void IRC.

> Perhaps aborting and --force option is more appropriate

Perhaps, but there are lots of warning messages anyways

> Well, or why shouldn't the utility itself solve simple conflicts related to destdir
Like we have 1 distribution and we know exactly what will break the system

I don't know what you mean, it does right here https://github.com/toluschr/xdeb/blob/master/xdeb#L247

**Comment by airpods69** [comment]
How do you stop the rewriting of bin / lib folder though? I want to install cloudflare warp-cli but it rewrites the bin (atleast a conflict does show up) and if I let it to continue, my void setup gets killed

**Comment by 2trvl** [comment]
@airpods69 I made [xbps-src package for warp-cli](https://github.com/void-linux/void-packages/pull/42005). As far as xdeb is concerned, you need to [resolve the conflict manually](https://github.com/toluschr/xdeb#file-conflicts).

**Comment by airpods69** [comment]
@2trvl thanks for the package and I did read how to resolve the conflict manually but that would mean deleting the bin and lib folders from destlib which from what I understand will break the cloudflare installer
